server:
  ssl:
    key-store: classpath:starless.p12  # 证书路径（放在 resources 目录下）
    key-store-password: starless         # 证书密码
    key-store-type: PKCS12             # 证书类型
    key-alias: starless-test               # 证书别名
  port: 8080
